### ISSUE TITLE
Whitespaces

### ISSUE THREAD

**Issue by ikopenkov** [artifact-project/tx-i18n#1]
Изначально проблема в том, что на живом проекте вот такое

```jsx
test
test
или{' '}
<a>
   Duo
</a>
.
```
преобразуется в

```js
"test test или<#4> <5> Duo </5> ."
```
Репозиторий с чистым проектом и воспроизводимым кейсом: [https://github.com/ikopenkov/tx-i18n-test](https://github.com/ikopenkov/tx-i18n-test)

Я добавил тест на это и выяснилось, что при тестах внутри либы преобразуется почти правильно, за исключением, что некоторые переносы строк все-таки съедаются без замены на пробелы:
```testtest или<#1><2>Duo</2>.```
[Ветка с тестом](https://github.com/artifact-project/tx-i18n/commit/cf2197d3ec8530cdcad2a3d76b08b40eb5999918#diff-25d902c24283ab8cfbac54dfa101ad31)

Если то же самое вставить в песочнице реакта, то результат такой: ```test test или <a>Duo</a>.```
[https://codepen.io/ikopenkov/pen/pmRQKw](https://codepen.io/ikopenkov/pen/pmRQKw)

Таким образом две проблемы:
1. При запуске на реальном проекте добавляются лишние пробелы
2. При запуске вебпака из джеста все работает почти правильно, за исключением, что съедаются разрывы между некоторыми текстовыми нодами

**Comment by RubaXa** [comment]
@ikopenkov Так, попробуй `+ tx-i18n@0.5.2`

**Comment by ikopenkov** [comment]
@RubaXa Вроде все отлично, спасибо!

**Comment by RubaXa** [comment]
Чё, серьёзно? ;]
